name: breast-thermo-mvp
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  # Core ML/DL
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - cudatoolkit=11.8   # only if using GPU

  # Data Handling
  - numpy=1.24.3
  - pandas=2.1.1
  - scikit-learn=1.3.1

  # Image Processing
  - opencv=4.8.1
  - pillow=10.0.1
  - scikit-image=0.21.0

  # Visualization
  - matplotlib=3.8.0
  - seaborn=0.13.0

  # Model Optimization & Explainability
  - optuna=3.3.0
  - shap=0.42.1
  - pip:
      - grad-cam==1.4.8
      - albumentations==1.3.1

  # Utilities
  - tqdm=4.66.1
